#!/bin/bash

# file install untuk komputer pribadi dan kerjaan menggunakan 
# versi 0.01
pil=("Install Aplikasi" "Install Settingan")
folins="$HOME/install/sjy-linux-desk"
echo "Masukkan pilihan : "
select pilihan in "${pil[@]}" Quit
do
    case $pilihan in
        "Install Aplikasi")
            echo "Sedang menginstall aplikasi kantor...."
            sudo apt update && sudo apt dist-upgrade -y
            sudo apt install -y curl htop zsh tmux ttf-mscorefonts-installer putty 
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P $HOME/Download
            wget https://download.teamviewer.com/download/linux/teamviewer_amd64.deb -P $HOME/Download
            
            ;;
        "Install Settingan")
            echo "Menginstall settingan...."
            cd $HOME
            mkdir install && cd install
            git clone "https://github.com/ygbr-dev/sjy-linux-desk.git"
            cp "$folins/*.ttf" /user/share/fonts/
            cp -r $folins/.zshrc $folins/.tmux.conf $folins/.putty $HOME
            echo "Selesai"
            ;;
        "Quit")
            echo "Selesai"
            break;;
            *)
            echo "Pilih yang benar"
    esac
    done

